version: '3'
services:
  database:
    image: mysql:latest
    container_name: cnt-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mel1
      MYSQL_DATABASE: proyectohotel

  backend:
    image: img-backend:0.0.1
    container_name: cnt-backend
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    image: img-frontend:0.0.1
    container_name: cnt-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
